### ISSUE TITLE
no default index.html

### ISSUE THREAD

**Issue by alamboley** [photonstorm/phaser3-typescript-project-template#1]
Hi Richard,

I'm considering Phaser again, seeing proper typescript template is awesome.

When cloning and building the demo, I get an error on my localhost since no basic .html is provided.
```
404 Not Found

/Users/aymeric/Documents/Workspace/TypeScript/phaser3-typescript-project-template-master/dist/index.html

(rollup-plugin-serve)
```

Would you mind to add a default one?

**Comment by photonstorm** [comment]
Oh yes, the gitignore had that folder by mistake. Fixed now.
