### ISSUE TITLE
Sourcemaps should be enabled by default

### ISSUE THREAD

**Issue by hearsid** [photonstorm/phaser3-typescript-project-template#10]
The project makes users write code in typescript and thus they must be able to find typescript files in source to put debug points at right place. Currently we need to go to minified/ transpiled js files to be able to debug.
If it sounds valid, I can create a PR for the same.

**Comment by entozoon** [comment]
It does, doesn't it? for the dev compilation anyway.

https://github.com/photonstorm/phaser3-typescript-project-template/blob/master/rollup.config.dev.js#L52
