### ISSUE TITLE
Repository as a template

### ISSUE THREAD

**Issue by playmono** [photonstorm/phaser3-typescript-project-template#11]
Hello guys,

Did you know the feature "repository as a template" from github? https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

I think this feature is extremely optimal for this project!

What do you think about this?

**Comment by JamesSkemp** [comment]
With 3.50 being released today and this being updated same-day, I'm ready to move over to this from my own template. Count me as a third person who would love to have the "Template repository" checkbox checked for this repo. :)
