### ISSUE TITLE
Hot-reload functionality

### ISSUE THREAD

**Issue by bhgsbatista** [photonstorm/phaser3-typescript-project-template#2]
Currently changing code causes the bundle to be rebuilt, but the user still has to refresh the page to see their changes. Is it possible to auto-reload the page on changes?

**Comment by geocine** [comment]
You can try my starter here https://github.com/geocine/phaser3-rollup-typescript , does not use `rollup-plugin-livereload` instead uses [nollup](https://github.com/PepsRyuu/nollup) which gives a better developer experience.

**Comment by KingCosmic** [comment]
🙏 would love to have this

**Comment by visuallization** [comment]
sweet @geocine !

I am wondering why the phaser team doesn't provide it out of the box?

**Comment by hearsid** [comment]
@photonstorm Hi, when will this PR get merged? It is a must have feature. Good work with Phaser.

**Comment by geocine** [comment]
> You can try my starter here https://github.com/geocine/phaser3-rollup-typescript , does not use `rollup-plugin-livereload` instead uses [nollup](https://github.com/PepsRyuu/nollup) which gives a better developer experience.
> 
> ![Demo](https://camo.githubusercontent.com/0c5ea4dba10baa6f84dd2d7f8a4f2e72c56fc55ad30f79b9a5d788daf083b705/68747470733a2f2f692e696d6775722e636f6d2f71586e744455532e676966)

I have updated the repository to use [vitejs](https://vitejs.dev/) which made it even faster and much stable.

**Comment by KerimG** [comment]
@geocine 

Why not use a widely used bundler like Webpack?

**Comment by geocine** [comment]
Its just preference, [rollup](https://rollupjs.org/guide/en/) is a widely used bundler as well . To simply put it this setup is faster than Webpack.

**Comment by KerimG** [comment]
@geocine I understand. Thank you.
