### ISSUE TITLE
Tiles not loaded

### ISSUE THREAD

**Issue by LeandroVCastro** [photonstorm/phaser3-typescript-project-template#28]
I started a new project using this repository.
The project runs everething okay when I just clone it and run "npm run watch".

But when I add some lines, this not runs like I expected.

This is my game.ts file:

```
import * as Phaser from "phaser";
import GroundPNG from "../dist/assets/[A]Grass4_pipo.png";
import mapJSON from "../dist/assets/map.json";

export default class Demo extends Phaser.Scene {
  constructor() {
    super("demo");
  }

  preload() {
    this.load.image("tiles", GroundPNG);
    this.load.tilemapTiledJSON("map", mapJSON);
  }

  create() {
    const map = this.make.tilemap({ key: "map" });
    const tileset = map.addTilesetImage("assets", "tiles");

    const ground = map.createLayer("ground", tileset, 0, 0);
  }
}

const config = {
  type: Phaser.AUTO,
  backgroundColor: "#125555",
  width: 800,
  height: 600,
  scene: Demo,
};

const game = new Phaser.Game(config);

```

This is my rollup.config.dev.mjs file?

```
import commonjs from "@rollup/plugin-commonjs";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import replace from "@rollup/plugin-replace";
import serve from "rollup-plugin-serve";
import typescript from "rollup-plugin-typescript2";
import json from "@rollup/plugin-json";
import image from "@rollup/plugin-image";
import dataUri from "@rollup/plugin-data-uri";

export default {
  //  Our game entry point (edit as required)
  input: ["./src/game.ts"],

  //  Where the build file is to be generated.
  //  Most games being built for distribution can use iife as the module type.
  //  You can also use 'umd' if you need to ingest your game into another system.
  //  If using Phaser 3.21 or **below**, add: `intro: 'var global = window;'` to the output object.
  output: {
    file: "./dist/game.js",
    name: "MyGame",
    format: "iife",
    sourcemap: true,
  },

  plugins: [
    //  Toggle the booleans here to enable / disable Phaser 3 features:
    replace({
      preventAssignment: true,
      "typeof CANVAS_RENDERER": JSON.stringify(true),
      "typeof WEBGL_RENDERER": JSON.stringify(true),
      "typeof WEBGL_DEBUG": JSON.stringify(true),
      "typeof EXPERIMENTAL": JSON.stringify(true),
      "typeof PLUGIN_CAMERA3D": JSON.stringify(false),
      "typeof PLUGIN_FBINSTANT": JSON.stringify(false),
      "typeof FEATURE_SOUND": JSON.stringify(true),
    }),

    //  Parse our .ts source files
    nodeResolve({
      extensions: [".ts", ".tsx"],
    }),

    //  We need to convert the Phaser 3 CJS modules into a format Rollup can use:
    commonjs({
      include: ["node_modules/eventemitter3/**", "node_modules/phaser/**"],
      exclude: [
        "node_modules/phaser/src/polyfills/requestAnimationFrame.js",
        "node_modules/phaser/src/phaser-esm.js",
      ],
      sourceMap: true,
      ignoreGlobal: true,
    }),

    //  See https://github.com/rollup/plugins/tree/master/packages/typescript for config options
    typescript(),

    //  See https://www.npmjs.com/package/rollup-plugin-serve for config options
    serve({
      open: true,
      contentBase: "dist",
      host: "localhost",
      port: 10001,
      headers: {
        "Access-Control-Allow-Origin": "*",
      },
    }),
    image(),
    json(),
    dataUri(),
  ],
};

```

My tsconfig.json:

```
{
    "compilerOptions": {
        "target": "es5",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "esModuleInterop": true
    },
    
    "include": [
        "./src/**/*",
        "**/*.ts",
        "index.d.ts",
        "**/*.png"
    ]
}

```

This is my assets files folder: https://filebin.net/uofi8tthkp55dabz

This is my folder structure: 
![image](https://github.com/photonstorm/phaser3-typescript-project-template/assets/11198617/c4b16647-8b6d-4fd2-a78d-231294183082)

And finally, this is the result of code running: 
![image](https://github.com/photonstorm/phaser3-typescript-project-template/assets/11198617/fe214345-2df6-4dca-a7da-edc019abbb14)

How you can see, nothing is loaded on screen to create my scene.
How could I fix it? Is this some issue related to rollup or something?

**Comment by photonstorm** [comment]
The error in the screenshot tells you the issue: You cannot use data URIs/base64 for images when using the Phaser Loader.

This is actually a really bad practice for game data full stop. I know it's common in the web dev world, but it wastes memory and CPU cycles so should be avoided in games.

If you absolutely have to use base64 assets (say for a Playable Ad network) then don't use the Phaser Loader. Just add the assets directly to the Texture Manager using the addBase64 method.

**Comment by LeandroVCastro** [comment]
But I'm not using base64 images. 
I'm using png files.
In my prints you can see exactly what files I'm using.

**Comment by LeandroVCastro** [comment]
I remaked my map.json file from zero, and now it works.
I think the problem is related to the image name and tileset name on map.json
Nothing related to base64 image or something like this (because how I said: I'm not using base64 files).

**Comment by photonstorm** [comment]
`import GroundPNG from "../dist/assets/[A]Grass4_pipo.png";`

You import a PNG, and it converts it to base64. That is the cause of the "Local Data URIs are not supported" error in the console.

**Comment by LeandroVCastro** [comment]
I didn't know this import convert image to base64.
The best way to do it is directly on 'this.load.image' function?

**Comment by photonstorm** [comment]
For images, yes, I would always `this.load.image` (or atlas, or spritesheet, or whatever you need for the game). The browser will load them async via http2 and it won't cost any bundling time either. For JSON it's a bit less important.

**Comment by LeandroVCastro** [comment]
Thanks for the explanation.
