### ISSUE TITLE
Unable to find module '.assets/...'

### ISSUE THREAD

**Issue by Qumeric** [photonstorm/phaser3-typescript-project-template#4]
Hi,

I have a Phaser 3 project in JS and I want to try to move it to typescript. Unfortunately, I am not able to figure out how to import image assets. I have tried a few different things from the web but nothing helps :(
My imports currently look like this:
import x from "./assets/x.png"

Could you please explain how to properly import assets?

**Comment by Girdacio** [comment]
You can try on preload method:
`this.load.image('logo', 'assets/phaser3-logo.png');`
then on create method:
`const logo = this.add.image(400, 70, 'logo');`

**Comment by laurentsorin** [comment]
@Qumeric Having issue importing png, I found the solution by adding `index.d.ts` with only the line `declare module '*.png'`
then in tsconfig.json : `"include": [
        "./src/**/*", "index.d.ts"
    ]`
