### ISSUE TITLE
Issue with Mapping

### ISSUE THREAD

**Issue by nramsey** [photonstorm/phaser3-typescript-project-template#9]
When I build this project and turn on source mapping in the tsconfig file like so:

```
{
    "compilerOptions": {
        "target": "es5",
        "moduleResolution": "node",
        "sourceMap": true,
        "module": "ES2015"
    },
    "include": [
        "./src/**/*"
    ]
} 
```

The mapping seems to be off by one when I turn on the debugger, here is an example:

![huh](https://user-images.githubusercontent.com/1013577/82736300-887fbe00-9cdd-11ea-87b7-482696a03292.png)

It is hitting an illogical point in the code because it is off by one. The map file is being created, but for some reason it is off by one line. I have not changed the rollup.js file any from what is supplied in the repository.

**Comment by photonstorm** [comment]
If you want a source map, it should be turned on in the Rollup config, not the TypeScript one. Then it won't be off by anything.
